require("jan.telescope")
require("jan.lsp")
require("jan.cmp")
require("jan.evilline")
require("jan.gitsigns")
require("jan.treesitter")
require("jan.nvim-tree")
require("jan.dressing")
require("nvim-autopairs").setup {}
require("jan.afkbuffers")
