#!/bin/zsh

pushd "$HOME/.dotfiles"

if ! [[ $(pwd) =~ ".dotfiles"$ ]]; then
    exit
fi

# Oh-my-zsh
if [[ ! -d "$ZSH" ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    rm $HOME/.zshrc
fi

FOLDERS=($(ls -d */))
IGNORE=("bin")

for folder in ${FOLDERS[@]}; do
    if [[ ! " ${IGNORE[*]} " =~ " ${folder} " ]]; then
        stow -R $folder
    fi
done

sudo stow -t /usr/local/bin/ -R bin
