#!/bin/zsh

pushd "$HOME/.dotfiles"

if ! [[ $(pwd) =~ ".dotfiles"$ ]]; then
    exit
fi

FOLDERS=($(ls -d */))
IGNORE=("bin")

for folder in ${FOLDERS[@]}; do
    if [[ ! " ${IGNORE[*]} " =~ " ${folder} " ]]; then
        stow -R $folder
    fi
done

sudo stow -t /usr/local/bin/ -R bin
