#!/bin/zsh

pushd $DOTFILES

# Oh-my-zsh
if [[ ! -d "$ZSH" ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    rm $HOME/.zshrc
fi

# Vim-plug
if [[ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim ]]; then
    sh -c "curl -fLo '${XDG_DATA_HOME:-$HOME/.local/share}'/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
fi

homeFolders=("mako" "nvim" "sway" "waybar" "wofi" "zsh" "alacritty")

for folder in ${homeFolders[@]}
do
    stow -R $folder
done

popd
